#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-xyzservices
Version  : 2022.9.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/29/55/be649be6e2e53ae2b611b7639c4ebd424f354e39a459b2b51981731735fb/xyzservices-2022.9.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/29/55/be649be6e2e53ae2b611b7639c4ebd424f354e39a459b2b51981731735fb/xyzservices-2022.9.0.tar.gz
Summary  : Source of XYZ tiles providers
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-xyzservices-data = %{version}-%{release}
Requires: pypi-xyzservices-license = %{version}-%{release}
Requires: pypi-xyzservices-python = %{version}-%{release}
Requires: pypi-xyzservices-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# xyzservices - Source of XYZ tiles providers
`xyzservices` is a lightweight library providing a repository of available XYZ services
offering raster basemap tiles. The repository is provided via Python API and as a
compressed JSON file.

%package data
Summary: data components for the pypi-xyzservices package.
Group: Data

%description data
data components for the pypi-xyzservices package.


%package license
Summary: license components for the pypi-xyzservices package.
Group: Default

%description license
license components for the pypi-xyzservices package.


%package python
Summary: python components for the pypi-xyzservices package.
Group: Default
Requires: pypi-xyzservices-python3 = %{version}-%{release}

%description python
python components for the pypi-xyzservices package.


%package python3
Summary: python3 components for the pypi-xyzservices package.
Group: Default
Requires: python3-core
Provides: pypi(xyzservices)

%description python3
python3 components for the pypi-xyzservices package.


%prep
%setup -q -n xyzservices-2022.9.0
cd %{_builddir}/xyzservices-2022.9.0
pushd ..
cp -a xyzservices-2022.9.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672263865
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-xyzservices
cp %{_builddir}/xyzservices-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-xyzservices/389c5ce5991fae5c036a609a7b8725b75633930b || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/xyzservices/providers.json

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-xyzservices/389c5ce5991fae5c036a609a7b8725b75633930b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
